# Generated by Django 5.2.4 on 2025-08-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('U7', 'Under 7'), ('U8', 'Under 8'), ('U9', 'Under 9'), ('U10', 'Under 10'), ('U11', 'Under 11'), ('U12', 'Under 12'), ('U13', 'Under 13'), ('U14', 'Under 14'), ('U15', 'Under 15'), ('U16', 'Under 16'), ('Minor', 'Minor'), ('U21', 'Under 21'), ('Reserve', 'reserve'), ('Senior', 'Senior')], max_length=20)),
                ('gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('men', 'Men'), ('women', 'Women'), ('mixed', 'Mixed')], max_length=10)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('hurling', 'Hurling'), ('camogie', 'Camogie')], max_length=10)),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
