# Generated by Django 5.2.4 on 2025-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='age_group',
            field=models.CharField(choices=[('U7', 'Under 7'), ('U8', 'Under 8'), ('U9', 'Under 9'), ('U10', 'Under 10'), ('U11', 'Under 11'), ('U12', 'Under 12'), ('U13', 'Under 13'), ('U14', 'Under 14'), ('U15', 'Under 15'), ('U16', 'Under 16'), ('Minor', 'Minor'), ('U21', 'Under 21'), ('Reserve', 'Reserve'), ('Senior', 'Senior')], max_length=20),
        ),
    ]
