# Generated by Django 5.2.4 on 2025-08-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitch',
            options={'verbose_name': 'Pitch', 'verbose_name_plural': 'Pitches'},
        ),
    ]
